#include <iostream>
#include <cstdio>
#include <cstring>
#include <string>
#include <cmath>
#include <algorithm>
#include <vector>
#include <cstdlib>
#include <sstream>
#include <fstream>
#include <functional>
#include <list>
#include <deque>
#include <queue>
#include <stack>
#include <map>
#include <set>
#include <bitset>
#include <cctype>
#include <ctime>
#include <utility>
#include <complex>
#define snuke(i,x) for (__typeof((x).begin()) i = (x).begin(); i != (x).end(); ++i)
#define OUT(x) std::cout<<(#x)<<":"<<(x)<<std::endl
#define ALL(v) (v).begin(), (v).end()
#define SZ(v) ((int)(v).size())
#define UNQ(x) sort(ALL(x)),(x).erase(unique(ALL(x)),(x).end())
#define CLR(a) memset((a), 0, sizeof(a))
#define x first
#define y second
#define mp make_pair
#define pb push_back
using namespace std;
long long pow_mod(long long p,long long n,long long mod){long long ret=1;for(;n;n>>=1){if(n&1)ret=ret*p%mod;p=p*p%mod;}return ret;}
template <class T> bool chmin(T& a, const T &b) {return b < a? a = b, 1: 0;}
template <class T> bool chmax(T& a, const T &b) {return b > a? a = b, 1: 0;}
typedef long long ll;

int f[1<<20];
class DistinguishableSetDiv1 {
        public:
        int count(vector<string> an) {
                int n = SZ(an), m = SZ(an[0]);
                CLR(f);
                for(int i = 0; i < n; ++i) {
                        for(int j = 0; j < i; ++j) {
                                int sta = 0;
                                for(int k = 0; k < m; ++k) if(an[i][k] == an[j][k]) sta |= (1<<k);
                                f[sta] = 1;
                        }
                }
                int ans = 0;
                for(int i = (1<<m)-1; i >= 0; --i) {
                        if(f[i]) {
                                for(int j = 0; j < m; ++j) if(i & (1<<j)) f[i^(1<<j)] = 1;
                        } else ++ans;
                }
                return ans;
        }
};

// CUT begin
// Array to vector converter
template <typename T> vector<T> vector_wrapper(T arr[], int n) { return vector<T>(arr, arr + n); }
#define to_vector(arr) vector_wrapper(arr, sizeof(arr) / sizeof(arr[0]))

template <typename T> string to_str(T t) { stringstream s; typeid(T) == typeid(string) ? s << "\"" << t << "\"" : s << t; return s.str(); }

bool do_test(vector<string> answer, int __expected, int caseNo) {
    cout << "  Testcase #" << caseNo << " ... ";

    time_t startClock = clock();
    DistinguishableSetDiv1 *instance = new DistinguishableSetDiv1();
    int __result = instance->count(answer);
    double elapsed = (double)(clock() - startClock) / CLOCKS_PER_SEC;
    delete instance;

    if (__result == __expected) {
        cout << "PASSED!" << " (" << elapsed << " seconds)" << endl;
        return true;
    }
    else {
        cout << "FAILED!" << " (" << elapsed << " seconds)" << endl;
        cout << "           Expected: " << to_str(__expected) << endl;
        cout << "           Received: " << to_str(__result) << endl;
        return false;
    }
}

bool run_testcase(int __no) {
    switch (__no) {
        case 0: {
            string answer[] = {
                "AA",
                "AB",
                "CC"
            };
            int __expected = 2;
            return do_test(to_vector(answer), __expected, __no);
        }
        case 1: {
            string answer[] = {
                "XYZ",
                "XYZ",
                "XYZ"
            };
            int __expected = 0;
            return do_test(to_vector(answer), __expected, __no);
        }
        case 2: {
            string answer[] = {
                "AAAA",
                "BACA",
                "CDCE"
            };
            int __expected = 11;
            return do_test(to_vector(answer), __expected, __no);
        }
        case 3: {
            string answer[] = {
                "XYZ",
                "XAB",
                "YAC"
            };
            int __expected = 5;
            return do_test(to_vector(answer), __expected, __no);
        }
        case 4: {
            string answer[] = {
                "XRFQUHISFHHZRRLFHXJD",
                "JKSPAZTUDULANQSJZCCE",
                "LLGCCTJJSSNDFHTHGOBJ",
                "IMLYEDHEHLKTXQXZLHLD",
                "BAHIHAPPQQBYEMYJSGNZ",
                "RZUQQUQDBDHEDQNMSEDI",
                "XEIBRHMLPBMIBHZRBRWE",
                "UDKZTZNNEQVDVEEONTZC",
                "ULMVULOXELDAOOBKPOXT",
                "FVYCBDSOWRSQEGOZUCYY",
                "NCZEQAQFRPBYMZANESDC",
                "LVVPCJQWLPWBRXHJYZQR",
                "ORPDTRQZLUCYRXPTGGRT",
                "XOWQLDBLCRETLTYGMOFX",
                "KHVCELXMTPGSFCISILEM",
                "CIHPEFVQUBQEINIPYGBT",
                "VHLCMVUUGAILLQARVWHR",
                "XZWHNEWNMYHHHSLTQIPW",
                "IYHVOIMLEWDDVBKKHHYU",
                "HFBOZPKPXBOHZVDPFRDL",
                "NGOLHBVOKVIRAMHCDRRA",
                "TFHUDKKICPWRVKEENCSX",
                "XDQYRYCUPTUKBDFEQROU",
                "GKLBXSHKUBKREARXYTRO",
                "PNYQTFUJWKDCVQFSKMEE",
                "OOWUPPSNJLDYBEQUJMDG",
                "WIIRAQLLEQPSENPTDHJO",
                "UMMVQERAQWIMESGHIRSN",
                "HJHOXWJCFSQCHEXZIRBY",
                "NJMSESZMMTBTCJJBHTDN",
                "NVRWZQYJHZJVLWPPQQDC",
                "JFYNQHPXCUMSSDORWMDD",
                "OMYZKPOBFTDQYBEQLVQN",
                "RCFJIWDEIGJWUKXFZNGF",
                "HLXHPBYAYOPSSXBCTGID",
                "MSCJEZODPWKWJIFYLDAM",
                "TQEOPHSIOBNCVPNZRBEG",
                "ZRCJZJJMNMAIEEWTOPDE",
                "SQIPGWQZZUFBLJMMSVBH",
                "HBQLGOGWFJAZAKOIGEHI",
                "BOJOXVBRQCZADRNLHUJP",
                "DLOFWFNCLWMOKVDJQGBJ",
                "IALNTYBASKPYWGDSLTWY",
                "PJNAGQLXWMIGOTVHRWKM",
                "HBMFHPZUIVVAGICNANMY",
                "AUEQNZYGYKUFLGMVYLRI",
                "GMIPWMCWAOUAIYQXAQFY",
                "CAFQIRLGEERMTBBPOFMO",
                "TIQDJICJBIJDIQTSHGBL",
                "NSXGVBVJGJZCSPFDAKMB",
                "SXGCNCUWIXJXRIDNJBWQ",
                "KYSENZHPJVQDSZFHBCDL",
                "ZMJRVMEGNCYAASEQSMFD",
                "JYHCZOJAQPLQBWJYJPFY",
                "RDYUYFMQTRVCREGQTSSJ",
                "HEBKAMLLBQMTVKPVRBLK",
                "UJPMNVEGNXSUDTHFGSTJ",
                "KFEHRTDJUQVRZKFNGJTT",
                "ILQLHXTPRMYBRDIIYNTT",
                "EPKDZPSFAMBJZRWIQPZH",
                "DYKUDUFBIYWMNIRNZKSA",
                "YVLXMJIEZHNCHXZKUEOC",
                "EKQSTHFSRZUPXFPLRZQQ",
                "GFUOFVAZBOBGBRYUYFOS",
                "GJHDQYPHXHZGMWWRRWQT",
                "NTBOMZINGYFOHOSAPJJM",
                "QJSEHOYYNQTAKUOWVYLD",
                "YQSGHMIWXRIPCDTJTRKG",
                "KFGUCWSZWEDVWXDDLNBI",
                "GKXJPSUIMGPWOXSSWKRU",
                "QWRNVWSGJUOQGNBXGXFU",
                "EWQUWIMSUDOLCGAXCUEO",
                "QUEWIHTQEBKKXAEVKSNG",
                "WERAMTXOQDCGYIFIPAAU",
                "DKGBMLWYDMEBSYDERBSJ",
                "GXQEHXOXZOTDAZEMMCKS",
                "QRVIPZOICJSIGKPNHDMI",
                "UFLUHRJTUVNMMJXBILKM",
                "UEUCOJSXPEFJMRFVIOQE",
                "METYPSCZDOLASFEGPWFE",
                "DMPRDUOOLEUXINXXHZWN",
                "NHNFPTNGSUMXHBQKXEAI",
                "IVHTKFQSGPFUYUBPNRVH",
                "LHEUIUHIYHQHEACRHULN",
                "JQJKMNZBGVJTCNONKVVI",
                "ENRJPTAWOLKZDVLPKLSQ",
                "IBKMRYZBVWLZKDIZYKYO",
                "XKOAFZRQMMIUNSJESKHN",
                "HTNTYVUWISLFCZIKABAP",
                "NILDDUJVFRJMKWHITBGB",
                "URJWSRGVUIKITVLWSWTX",
                "NCLZASJUVQXPJGOCZWXU",
                "HJEAGRYYNRXBWICWCMSY",
                "EQPNWDRWAQSHZWJGNJEA",
                "CEDYOGXRUPRYFINEMFCO",
                "VUXXQIDDRJDTNHUCPRVJ",
                "GOJOWYUKDWABQZYIHDLA",
                "MQUCZOGOHDZNTKDRJXCO",
                "TEPLENTLSGMHXIJYYRPF",
                "WOUPBAGKXIYTNQGTFAGY",
                "ISFHCQGCHVHDLESMEAYD",
                "LZYAPFTUHZSPUZZYPFBY",
                "CKBNOVCUYAAJBYJQDELM",
                "DFEXFDWWKZVMJYBAWFUU",
                "IUFJVOAAUNNXSTXZWVWG",
                "UTUFRXFPDALLWQURGUSA",
                "HHYCAXBYSZGOSATMXZDA",
                "BPNZFIRMCLOMSOQULRSF",
                "TYTNAPBXQFARUNSBXJPC",
                "WEOQSEKEXCLSCFGCWHCM",
                "MEFITXKRJZTFFJYYPIEO",
                "NPHPWNUSWYGLCNTVNFOY",
                "HHDMSDMHMQWZIFQEUMZQ",
                "KFDMVZKIEYGNILCAPOKD",
                "HICPNUTHJSZTADIVCSFI",
                "SLYAYADNQPQXXUOMRITA",
                "CUTEXBZBVEMORKQQMVFC",
                "KWAHSOTJYOJDLFHKIJME",
                "PAUJMKZYGEASCCCVTXGR",
                "MQWXXGJFPVJGXDRJQQHY",
                "XIQBMSYFQFXEXVDUBMBS",
                "KLBHQSRILAGKKXLXRMCJ",
                "RBPQXSKAHLTRYUAROTZZ",
                "WGJGFXDYJIICJXSISEJZ",
                "RESSYUJMQIOMQZSXWYWH",
                "GGLRFFAZJJADNSVNPGBF",
                "QPRJRJGNJEXPMIHSOHRZ",
                "SSEHMZWBHXIYPZJGLPVU",
                "WSKIDTARCUSUMXBAYXCG",
                "WKGNMPTXGRTCJFLOYNHA",
                "HAWVXZWXYAFVMNKYCEXL",
                "XTNIYAXXQEZZEWVDXTDW",
                "TITHWDGAJFLGYBPZDOYT",
                "SXTZVQETJHRCSKLONRQZ",
                "ZCFZFWYIKYEFYXGTNKOY",
                "UHCMRNCHHSIGWPHDMIMY",
                "GSFERLAGYQESAGGTTKAC",
                "EKIDASGOCUMIMUPDFRJF",
                "JPZJVFDRRFTYQEBSWHGY",
                "ESIQOZWUSHBEXBPSIULA",
                "CFYSJBMHISHOMRHBTDXL",
                "KYRHZHCKBNKFUKXFLLMV",
                "DVKQNRRIWQVIONSQWUAZ",
                "JKFEWELJQYGTTSLILCQH",
                "SMQJBKZXGZWPLDVJIHSY",
                "HYRCRDNCHDMCRELUOMRU",
                "LQLYTJHBQZBZZVBSAOXJ",
                "UJLNPYIDKBZXTKXPTESL",
                "FUKHROZRCWAYHOOWMYBZ",
                "BAYXLWMECESIACPRQQIV",
                "PLVYZJVLJYMLZNIKJUQL",
                "AIVDNMUFFFAUQYSRHPCR",
                "OREPEMZPIRAKCYNPMKUR",
                "RXLJVGAEXEXLVBCBPDQX",
                "VTKZRZQDJKXCJILEQNLO",
                "SIBPMERBHJBECLDVKTBW",
                "GYARIMWZZJNTRQJDUCHE",
                "LIIQVONFJODPOEHXSFYT",
                "ONNHDYNACUENCOFXCTEO",
                "JKDYQMXITVDJIQRNQENS",
                "ATICKNBMGHAQRGQHUNRO",
                "IVXSLQFEUVWWOEAYSBNA",
                "JPQAXIKSVBGFWFXKWDOS",
                "AKPORPPJTELCTEETMQLI",
                "STNOANAWSOPSBGISXXDQ",
                "DQUZUZSHPFRJAGAATAZL",
                "RODSWMMTLRMPHGOCHGLX",
                "NCINKIPEJOPCETWAHIWS",
                "BIHKOXOWFZVSDDHOOXSZ",
                "LJBQCXQJHOEIWNSNLHLQ",
                "IIJMNSCBPWABFBRKAJVH",
                "YZPWNKJYRWQBEBNUURVJ",
                "NYKTBDFCNAJLABJPLTPE",
                "RFFYJVSDMNOCLZXNECRR",
                "CAEEDOTOJIUAQAYZXQEJ",
                "GSNTTKIYMZPPCUTFKPUT",
                "XQVPQUOPMSZULMOEZWEL",
                "YUCAQYHANDVMUQCMKQCZ",
                "LDTYRJCQIHCGDEIVCPVR",
                "TSEPIGBVYDUJGPJYZOQH",
                "XSPAZXVBOSVJKZYSHAPF",
                "FJROZAOAOEHLXWNYVKBL",
                "EWVQVVLCXAKFKDTLFHLU",
                "NUHKQXKNHMAOIVEETPIQ",
                "QUVAXQNDZYZNSIZKFKZP",
                "WZDEXHKQXVIPPGPPWESW",
                "CTLWBKGJUHYSGDZDMJVL",
                "GEAWKPNITFGXYRTBEBKY",
                "IKTRNSUABQLKWMGGDVQZ",
                "AXYAQUDUXOVGAOZOGTQJ",
                "LDTHRBPXWGWYFWAXQESO",
                "UNWUDVKLQAWCEQLXTDUS",
                "JSQQPTNFXHVTWRNZOYKH",
                "AJLEBWEUZYOKRFAGAQNZ",
                "XJSUCFVTFIAGRLKSJQML",
                "PBVGIYOKODJNOBHTGDMM",
                "NOSEBEWKXKVMNTUVRKFH",
                "NQUCREVAJJOWXICYMYKJ",
                "IGXWBRTSBBBRRXTLDOLO",
                "XZKWHOUVMGHXMEVPYOHB",
                "RKSLILWLBHAAIMWPBSMP",
                "ZTMNAHDYYMBPXWCFHYSL",
                "HULPHKGKCTZBMOROXUOV",
                "GQNFMPKVQFIXZWNIGVUK",
                "OWODKFRJBGFHYUNMLZJB",
                "GSBGQQQWLLICHWFTDYCE",
                "GJOGDBSRCEULYVTONJMZ",
                "UUBDRIWWIZBPIPVOSQFW",
                "UZHSXAIKKULGOOKHYGEH",
                "FFYQWTEOLJKHKUZJUHWG",
                "DHNSYZBWFFDNMBDIXJYK",
                "ULSGFTQZDMGGVVYTUASZ",
                "HVOWZTEYCFIYQAFVUXWX",
                "JEFGZECTGUVPPLLQFSOJ",
                "XXKPZPMTMISXNYFOEHKM",
                "BFBTSPJZJALGZVXYMJUA",
                "TMZIMEXQMHCPOGIIXUIG",
                "UTOTOLTCWNCPABYMFXFT",
                "GJJWPTEMNMSJHGEXTYZP",
                "LBFNEFCKEJFKSOGIIMWX",
                "ZRHIZLGTLHIZJPMNUQZY",
                "ZFKSVSCFFADGRKORXWMJ",
                "EUIPKWEGPEHQLTKIMMOR",
                "PRXIDNZCKLLQIVFUUJCL",
                "PLBAFMJRAZKRQJAVWBXI",
                "NLYXIFTEPVPGHTJMHUDJ",
                "TNBLWBGUCDFRQFQZLJFC",
                "FVIMQRAXLFGGSJRQKXMP",
                "DRGTXXUIGAMNXUBPOBMB",
                "GUIAEZSQZFFCYOXVLUFT",
                "WTJVOKKCMYFUSNVYNNPO",
                "UUQTIPQVLYRHRAEHMOLA",
                "ORVJGSHTHWHCTZXDRPZC",
                "PSMJUSQGJEHXVCGDUOXD",
                "MGFFIEJBWKFLCTUWMNEV",
                "RLSOPZRLPQPBZWJJBUKZ",
                "ERKILHGXWKSPWMFLNYXC",
                "ROGQKPBNJNMPEZXPIDOE",
                "NITLVAZIYYNPMTHYKKMT",
                "XAICZHTHKKNZSINPIMAJ",
                "KNYYIIWSSINQJXUKEPUQ",
                "ZHPUSEJAQJJCYKAGUXAM",
                "HNEQKADOSXERGWNYCXZT",
                "IKVHWYNQVQFCDLVOMYEE",
                "VLXBJLALKBGSNCBKCRCX",
                "HHBKVWAHUFNRSMVBZXML",
                "ATGNXHZZYCYFLZSGYSPS",
                "ZEMRRJSSGHEGCKVBTVCS",
                "XAZIZRRXMGSLLGFEPXWX",
                "GCFKOALIVNCUNBDPTWOH",
                "CISNQXTHXQEFULQLOBTJ",
                "PVGEYJVTHMAJUTZNSSUR",
                "KBXFMNQAOLMFISMGDJAK",
                "VCTSVUFQNZHXCECPTURK",
                "HFPPZDYCNYOIAKAYEFQR",
                "HXPJETAXQUHXBZNBCLDR",
                "LUANECNKKDCRBTCFOFEG",
                "BMECNTDPGJJRDJGJNUTX",
                "XXQASVHJAMPBATDNOJEU",
                "SNNVYWGMQZLPXCQRZXAZ",
                "LQCLLHAAQFWKUMHTINHY",
                "NSNMWFDVDEWOWACHKCJC",
                "JGNESUZAIGAXAPLZVQWA",
                "UVQSVSAFXJKGPXKJRLLB",
                "RLYSBLTYCPYWKORIJRPG",
                "CZMUWZDQKPRECSYDDRDF",
                "GBETQVBBOQHQQVKOWQEH",
                "FWNHOLNTEQZKUDFMAGNO",
                "XWEPRPDOFIXMGKVWXKPB",
                "DONZTTLVZYJYUQPNHVDO",
                "DAALMXHJKWKNNAMITZEU",
                "ZPVVFMIMHMAKOCVBAEMK",
                "BZZQZNYUMEOLULGZYQMF",
                "EOSTRPURUIDVHELGRLAF",
                "QRQKCYJCQXIVMAOFPKYJ",
                "SBGAHTIYFLDVEVFGVQLL",
                "QTGEVWJMGHWBKEDRYLRD",
                "YWACTHLOXWBPPKTMGEYP",
                "NWQXBTQZGJEFHEJANUQK",
                "QUCHEXTKCSZPQRPRKHST",
                "RYAYEJBRETEWNGGRDZEF",
                "TFXKXMDJTWCMUENZOQQU",
                "JUSZCYSGAWNTCKFBYJKU",
                "HPIBTXCJNVFZRYYUWQCY",
                "PRUTEZUCKGYRVJVRGZAU",
                "UGVOGVKELMDCDXVJYROJ",
                "AMCXVXOEZRAVZVJFQTLD",
                "HOINNDWMXKVXZZUWZLCY",
                "CCTDXFIPYTVIKDXXIVJF",
                "GGEHGBFHMIFQKYTKFDBG",
                "YWOKZLIIGTPOCWXKXDRL",
                "NWDXWYJCBLIBHYMJLWTT",
                "RIKTGHDFMUQZSTZRTITU",
                "TDYDBMMMIFHZPRVWZYBN",
                "VUNPPMGJWZFQEFTFRHTB",
                "OBDDUYBTYFJVZYLQMRZI",
                "RHYVMTDEAYHQZKUUKXPJ",
                "CAEDYRWKJXTCETZTNCZP",
                "BGGCTCYDZQOEQVHPMFZV",
                "DUXJOXCBBBSEIYHBAFGC",
                "VVGOSPDEVECYZBHNYKQC",
                "NIGXJNAJVHLSERGWJLCE",
                "SEERGNGGZYINGPKPELBB",
                "UMWYGEWPSYVKDZDLMJRM",
                "HCBPTLHZWIBQWZQEDMTX",
                "LQHQPKDEVUSEYTUREBRD",
                "LUVHTOMYAHWNYFFPQITN",
                "FLSDGOVLPOQCINJDBXDC",
                "HZRFHXWXHSMMFESMSPZJ",
                "DPLNCXQGWTIDVBKCAHBI",
                "ZNWESOQMDPWIGJVLILRF",
                "HBICCTEDCHNBUJHOAYBD",
                "PZOYKJLTVCYCFGGHBMMD",
                "TZGPLOELOHQDIEDSOOLL",
                "QJPXSXFVJTBCVHRIVXTJ",
                "ELPOQSHGJSTZEKXYHETQ",
                "ZUSUELCZLXLPJCGBUNJD",
                "HCFLMEJVKFLLBFIFSMFD",
                "KSVVUBYQOJWVNDJBJUWT",
                "ZHEBMOGEBNKLFFIZGISU",
                "RORERAFAVBVWKBZWQGCR",
                "TMEBROCZWUVNKNRDPYDM",
                "BALLEKJUQLNMATPTHRTD",
                "OQSYDJCVJHHKKSVODEKV",
                "RXJTQYPZSKCGAUGEFKBQ",
                "UKAEDXUIBEFUDPQTNFUF",
                "PWNPSUVZGWPAHPEMMYWP",
                "EBLHSBCIGWNVUDNMZILF",
                "HCIOROCFNYWTZIBULDCS",
                "CRPWUCLVNYBUBJKUXMAM",
                "KYGLGJFSOJMQBDPVIATV",
                "AURBFBWEPYRZWZMFKUZY",
                "DNREQICAIVVKROMWRKCG",
                "KTHGUWNEQOFVBYCUGGUQ",
                "DSAUGMSAYUGIQQRMOETE",
                "TYBWYDQEJLUMDUIJJALJ",
                "XUSPKJBYPUEKUFHULXYU",
                "KUJNRRZCUKLTEDIQOJOG",
                "GUQCCZXNZVJJSSXJMWLI",
                "IWBNCJFSUUYAQRFSQCHP",
                "ZRZRLYCZUNHEMIROTXIO",
                "THQLAVGQXNIZGJQUHTTD",
                "IDHUNZKHYTVTCLECJMUG",
                "ACFINYCUTYXBBFWOGIXG",
                "BUZFIFHRSEZUIFCWFHQY",
                "FOBITXYBIWHJQIRYNAPH",
                "EPDNWGJDPBDUPEEKCCNM",
                "YUVPCOPSPHBTYFIUNRZC",
                "TCYKGCXKEKWFFUWJILBX",
                "SDTQKBMXVNBQPZAWBZGH",
                "KFMRZIAHWEHQJAHTDVSY",
                "JTOYURWVQFEAKTTJDWSZ",
                "ABQLBZGFWYFFTUGNLEKB",
                "JOETJZENVZMXAEIEFQJC",
                "QQHJKPYVUIZFZFZIEFXA",
                "EMXHQILWAWYRMHAXZZUT",
                "JVYICZTHHQJNCIUVSHTT",
                "DTKQCMPBLLWXJVHLWASD",
                "TDTXMNSEVNXAGHSJUHKH",
                "VHGEEOPCOKIHNBFZQZGN",
                "NDOTNGEJQPSNYZRCNIGD",
                "UONIPUJGTPVITJEISITK",
                "ZLXXKQBZAIDVWQDOKMWF",
                "EROZBUHVCAFCNEBAWFZW",
                "PETNWYBINXORREQUYZPC",
                "BWEOCIOYPQWEWSRTQVBD",
                "URWLXMFVNWYOSEFWOVWD",
                "LVHKNBDFWGJQYHCXWJTJ",
                "GTAAZFXOATTOOBYBCDHA",
                "JSQJZUHVECHKVHKWMJKO",
                "DECRHCVLFELPYDYZYHXE",
                "JEOGLADZKPPPVSIEUDRA",
                "JERHIRHIZEMKKCTXEYYQ",
                "PNFNHORETLGFPXMZQVHP",
                "BVCNZXKGVIWMYEZFSTJN",
                "EPSTOHTFECWGYATZXGFU",
                "QCHOGIWABHPFZKZNRUUV",
                "WRDWTZWRFDNVFWMNFIPG",
                "PHMQRLEKHAHDRLALKYER",
                "BTMJQAYVIOBAVNSOAYYH",
                "ZFNSQPFCNJTQDIZVIYQT",
                "OTVLJNZJMXTLEIDXXJZM",
                "UVCZFCUNAMIQGFBPVAAH",
                "ZVUDDZCCKEOHZRIGTDTV",
                "RELXJOOEOPNPKJUQLXSV",
                "BHECYNITSDOJJBJTPXZF",
                "MPUZYOPJNJHOQLSQAAJS",
                "GZEPANKRKMWZBSABJPNW",
                "YWNRJFHKIRCOSIFVVSMI",
                "ELJHFJIOAXLYTYRDFZPN",
                "SRDKCJFXDUHHHQOMZYBZ",
                "YOATOTWTULJOFMBHXGGA",
                "COJJGZYIAZJYPLRDFQYZ",
                "DHOIWPRVXYYCOHLUHLEJ",
                "KOHZZAEEQDGWMUEKLYGK",
                "YEMOLAKULPDYDMZCPGJF",
                "LPDXLIIYIOIGUXWFZGCK",
                "VHKYUKDJQMQBDUAOEKMM",
                "AWUUTQASYEFULPUFBXQT",
                "LHWODXCJJQXKPREIJGDH",
                "KKDWZYDDXWWJFVXISCRB",
                "UOLJHSUSYXBJHHHIFMNC",
                "IMNNHNXBRQCLGQXNKRHI",
                "QLTZSCJZPXDZJRPSEMTX",
                "DXIJNHZXAIIQTDRNGBMX",
                "AQWLJLDPAWMFTWQJERIE",
                "ASXVWQJCTXZVNXGYJLNL",
                "JZQFYGQEYAKATHVPAGTT",
                "EUPTTXSEJHPUJFZHORLM",
                "SVMLFJCFQXAWTRRMPJRA",
                "TGUCOWJCNWOFTCSYNWFD",
                "TGBMZTZOEQOXYLBMHKOW",
                "IEECGWCUTIZOQDBPWCGA",
                "UWASHBFQOTPYATAGPDCK",
                "NEZFHCWFECHYBHSILXBZ",
                "TQXTJABAFGNUMMZVQXAU",
                "CHUDRONCMODHGCCRCDSH",
                "LHBXVCSLCUHEEDJVRWZF",
                "NCMTEOLHUFQFOUFJYXUA",
                "UBGYEPTVOSDDUPWAGJJA",
                "QCHEWMNWMJZGKFEQXZON",
                "RRQNIOPOAZQSBAZZMOXY",
                "YWGKEMBDLRQEIGTQWJHW",
                "KZRNZQOMELMCKVPOHQRT",
                "HHZRPTJNEQMOSDDRTRFX",
                "CUCOPRCYJVTQCTJTOSJS",
                "LVIDYLWRCEOGYSVPJZPS",
                "VJKZETVSOEMZZWEXHAOL",
                "GETEZQVIQLDNWPMALJUZ",
                "NIAOEELNGBYNIRTHKRRA",
                "EWNAMBCZLYYAGAPKGAXM",
                "EXBMQXVAOOASLPSZTWYG",
                "UWGAYVMEYLSCKUQARNBH",
                "BDZOVTNOPLULJCNHYZLY",
                "MEAWASYTHZAIFBXAWMON",
                "YKYJMLRMMEKAKMYMEWFL",
                "WHWBIVDGHRTFDRPREIEQ",
                "OOQBBONHNTVLCRONORTV",
                "KNDNEUEJCKBSBUTCKHLX",
                "CGIEZWTNNNLXAOMGKTRO",
                "DTGEPAIZJUXLCHREGLTT",
                "AETAUHIEAAUGVBKKDVLM",
                "RIZVSSZYFVTFBOHWWQCW",
                "QXENARXDMIRFTSANKANS",
                "XGXYVFWTXZRPYWCANBDB",
                "LWGGOGTAIGSFPQEMXAFU",
                "BWLBSNBFQGGBCMIQVDRD",
                "MLLDBRPARUWVQHYLUAQM",
                "GZOLNYBKDUORGBUJSJML",
                "DIGWQHHMHZZPAPAQPEAS",
                "YQKGRESJOEVTODRGKAVT",
                "AWJCLLSAPTUQJEYBLQMZ",
                "WJUNNOTZOQVOMERZRJZH",
                "EWZQAXRLQFMOPJBEXXDL",
                "NYCCEVBWGDFLZEBBDUPT",
                "ZBKOMLULKYXAYZCFWFDC",
                "KINJOQNRKCNMFXCSKXDX",
                "VCXVDBAZIFCTNPEDIRXS",
                "TMEBJHTVEYSBDPWGSZGB",
                "EKUUBYZJSWCLKIOTPHPV",
                "IJYLZXTTWZUCJQYNRYWJ",
                "WYWHJLCYUTWEDUPETJXP",
                "KUUWKUJDUFMRGLAPYEPS",
                "YNXDKOJDZGVMCPKPLVSG",
                "AHZISZZQFPKFEJIOATSZ",
                "ANNEEXTPSOVVVUFNVFFB",
                "WPIABTPBMHCOUQTYPOPK",
                "CLHXFMMDRRENJMOMHFNU",
                "MPIIHBIZQXLSISSQGETA",
                "YZNJNDVVIIPWZXEJBMIR",
                "KVLUNDKVKDVIELRSQMNB",
                "WCXVBEGCSQVELJZAOLWY",
                "RTGVEZNVLCYJGVFIBNMU",
                "EKYPTZSJLOICHQXOQNLD",
                "PJNWEUGIHSCNECDXCVHN",
                "LRRUHQIZDVFVESTLOZTX",
                "TVLYXOXBLGQYXHUHAFIF",
                "ANAFHTQVUJVOGGOFWLHJ",
                "SXHPHBYHGHMJWPOEKGBF",
                "PWVXCJCAULJMJSESUEZC",
                "LNLICBONHPSYOPVSYATU",
                "LCHWXNORRPVFDJPFKDSS",
                "UMSKBODBQYWDCFAZSQSL",
                "IOSLZHSJMNDJZWTDMYEC",
                "YCFBHHABAVNIJFTIPLTB",
                "AXMCVIFHGLLFOQIXAIZA",
                "DOIOVDYKQUORTATOIAVR",
                "NGYDYGBYQCAUQIKLNLWE",
                "FMXYMQOXSJOFRMJRSKSI",
                "OSEEDRPQCNWJZTHOJVLD",
                "GZJZLSQFEINSDUYGLNWP",
                "DVYCOHQAEDDKCMLPGBUM",
                "MKEPGCVRSTGVOGZFNSFR",
                "XIDAXOPDRMQFYWUEBRVT",
                "NDQDJRIYLNRJYULVKAAB",
                "OSHMPDQQVNLISDNDUWBI",
                "JSTJOEGYGHCVZLJOOAGL",
                "PRVIWJLTFNBQHUAWYGUG",
                "PWBPHLFYNOJCHFKEOYXV",
                "LYLUUNQUWNALLECTRITE",
                "WCGDJTJZRGUEGIYAVRWR",
                "EXFPBHKURDYPIGTRZERS",
                "LLYRVZURQQKWNPNQZYKQ",
                "DKGNRBFSFYNSLLKHKEYA",
                "WKYKAMCBMPRPBZDSCKNK",
                "IACTLMAYSAYPLZBNLFQX",
                "WHOYJTSLDFVNFAJTOJRH",
                "MRYZQBMDICAFLRFWKXKQ",
                "FHDMHMFWYYFKSFLKGXOQ",
                "BQXOHCLUCXKJEPVMEDIC",
                "BNOTUZGAYUSBMQPUUCQY",
                "ZCHERDSXGABJPPFJQLLQ",
                "FFRTVJNSNFQPHYTBDNYJ",
                "PAUERZPKKCARJULFFAZS",
                "IPHRPCSUPTFEVAKOZBYM",
                "FBFPVSWCVVWDMGUEIPYA",
                "KEGFGTTHWUTEVBTSVRUQ",
                "MSVAYSGJHFLTLTATMVAL",
                "PWPMXKEUBALPVGPTYYCH",
                "FNAQHALVYLINJXAIHGDI",
                "JOZEWPZXPCEURHMAJXYH",
                "IGXUEZCNFFYQTXWSOWPD",
                "YVXRCJUOGSXRYUNETPSB",
                "VSTQPQIEMZJMVJFZSZPB",
                "RNUSJHWFWQITIBMYRWEF",
                "WNRRWXSRYIUQVOIGXGLV",
                "XTRFVDDOZJUVZLOXKHOJ",
                "RKBMYJSXPGTOZKUWPZLO",
                "JFMKSCHDLYOCIPOJAJGR",
                "RBGQNANCBYTMFHWXJGAV",
                "GQXOFOZHZIZQLFIZHVDK",
                "VWXADVAPDAKJTJAYZZGY",
                "JHQVMZUVUZFSYEUBCUSF",
                "XCPQOPQNQYMAFCVTBROY",
                "QWSOCMSEHKKEPBUDSMSI",
                "LEIQJDKMWAMNYEDDRXHY",
                "KTEZWAEOMWXXDHQMLCAJ",
                "CNYDREGKBPKLLOMHQQYD",
                "NVCQCSEPUGBZTZENDMZF",
                "DKSOAFYRVWUKTYCXRIPL",
                "PQMKRQXVCXCGJUWJBWAX",
                "UWJNVMNOUEBLUOWLEVIJ",
                "UMRDHNNIKPHEORUJFJZB",
                "NANJOLWVGFEBRVGAKTLU",
                "LUBZNXKSGJWVJLEYWAVE",
                "HZHBWOBGJMDUJGTWDDPL",
                "MNGYYMWWORCWSKXOAAWJ",
                "PZEYFXUKDLVPYDPYPNWE",
                "EZCYLBOLBLUSMYQSYLEB",
                "YASZDIZVVWBCXFCIGRTJ",
                "ENCQOSKOFPRGPJFUTGRR",
                "CSVZZXHFQCRUSTLGNVWV",
                "KNBBYIYSQPLTKIUJFERY",
                "GISYDFGSBCNNPQROAPIR",
                "EVMQDGAIKRITBBTEGAWJ",
                "EMZUCQKFHSWLPIESQECD",
                "XLWYMREURCGWOFSTXCYE",
                "WURLEVFWZHZYSXWGPCDI",
                "FJETOYMNCKRYGILMGQJF",
                "AIGSICBZHEHMNOFDMUQP",
                "GJPPTBBZTMHTVNOFRPEY",
                "VLKKBSPOOHFWQULJXPLT",
                "BSOYHCDYTHXQVJAWBPMR",
                "WROOOZALOLGSFVQMZUKV",
                "DJLYVOVYFHQCBESPFSCW",
                "DJOKGEWHAJCEUQCPEZOL",
                "JGPMKIBRAFPGQDQWKPGK",
                "YIQUAVKGUYSFGHRQRUJS",
                "AZASESROHXBHHRCIOMOL",
                "MIQSSKKJGTBIUDBZWSPF",
                "PQNWKPGYDXJRFCJXMVHU",
                "QKDLOEMMYBRNUELEVSEA",
                "PORWSCUGXDAQPDDFJPRH",
                "QLWKRIQNCVNTLFPDJLJH",
                "QLXGPALYRFIHQEUHMMWQ",
                "HKJURBXAMIJFUILLKYLB",
                "DTLVYHDMTBDDNOXEPXHE",
                "FSJBBWMNUYRATCVRLAGE",
                "CLHPZHUREDVLXGNACZOW",
                "ZFWTJUMUUUAWFKMHRIYV",
                "NVIKBVLDXBBYGATRUGLO",
                "CLNIXZROHRLWMUGPRRUQ",
                "SVPAXIRRQEITSVBPWUGF",
                "LRBZNHOFBIVVFMYFVRWL",
                "WGEODHFZDLEOFFNSPDZS",
                "NXNVJLAGDWSBFYRIIYIL",
                "KOCRURLLVLDKKSFVGFCL",
                "EWMJWFTEDBSNSUGMLSZI",
                "FCTPUYMAGOLKMZVJEONI",
                "SFXKBGYPYXXDBSUVTIYZ",
                "XLJJNGSRUIBOPBYTHWIF",
                "VHKWAGUVOSUNFFZSLTMH",
                "BNWTQUMXTWEODQNFWHAN",
                "BWCGBBBOVNYYCURTQFSL",
                "BXCHNPMMWPBXLDDPFGFC",
                "TDCWXWRQBJBFIFMYUAMQ",
                "PNPDQVUXBZBVDETCAMUB",
                "XYGIDUGYVUQMHIPZDLXE",
                "LYBQCWUEKRGIPOSUJAUG",
                "UNSBVKAYXZEKAICEEXJP",
                "QRZHHTBSTYYNLTQGFQEC",
                "SINSQPYXOHOEAPNIIPAB",
                "NZQYUGGZYKBQUQKNGLMU",
                "SABTRODBFDEUEUUYCAXA",
                "MBTHRFWZQIWLKXGDNJET",
                "MIPTEKRGMRIZUBINJENZ",
                "OJMAISDVBHQQRGJVSCDE",
                "VLFPNNDYRSXHBMHJEKGG",
                "TXYKFJHZLKFJWLYLYDJS",
                "VIBYUJJBVQJRPHDWSLVD",
                "XAMVNNGMSRGQCHOYSYZO",
                "QKFHRKDJVAPVCDQQSZEL",
                "QKDURRTKRUAJFHQYRTKP",
                "TZKYEAOXZSKSENMXGHHA",
                "EJJLQCJIVTXRUJPBJFAL",
                "XMDBBRAHBIJFTVQKXBUU",
                "XTNREEUNJUYIGDLHVMRW",
                "WADPXTBUUXPRSCLWHFKS",
                "CKBIQMSLYJJWLMMJHNFD",
                "NUXFZICIPOATYDCOSWBQ",
                "HMPSABDJQJNDFMJGWLQL",
                "ZTFZWJQOHTHOIWGIZMSP",
                "XHTCTELPRBCSUJRTUJHB",
                "DQPNOYVNKPDHYYLTEYIV",
                "ANNWYGPTQZUVRKIGKFTU",
                "XYDVYQPEPZZROONNVFGN",
                "GCKXOUDYZZUWZZUAQLEH",
                "MGYBUNQRSYGAASYPMDNM",
                "EIKGHGGZRMGGUGJRWZKQ",
                "XRRZJPOWUEKZMWFVDNXW",
                "BFCWMLPIMZAJSRJCIZAD",
                "DMCRIJPNYMKZRMXFAMPM",
                "OQYGHJKQIKTMYXFHGUWG",
                "GGHYVHFVTVJJLHQSQAIB",
                "NDNLAUUIPRQVXYVSFBPA",
                "YZKJICBZCMAPRPDUJXEA",
                "OVWOVTIAWYCUZOFHQJIT",
                "VKKOZNILNPLBMJRHFAJB",
                "ANYZCDISMRNJBAADPKQC",
                "ZBGLNXUSXFVXTTYVZHPN",
                "YDZBDZGULWXLYDYNCVFC",
                "AABTWAQVHGKHJJKOKRIY",
                "NHLNMJAPGHRHIUCEUTBD",
                "ZLMKXXAJQKHFSSVGEXVM",
                "FOTNJYTFRWJSJXEGUGSM",
                "QBSKWNRCMOORFKGQIBVB",
                "XGVHEZPAHHPZLHKHWDLK",
                "TZCAJKQTMOUJUPQAQIDX",
                "PSXCBJJZOWJJWLKHWABK",
                "QXTNPMNHUSHLKGQNPBMF",
                "YWOUJADHBERTENGVBUCV",
                "OJIZPAMGCBNAXCUICZQF",
                "EHZKUHFVDJSSTDTKDFTF",
                "IGHFKDQNDGUJNVTKDYHG",
                "HCACHTPMBISJOBRZFHOI",
                "NKRCIKONKWVTAWYHPNTQ",
                "XNALPTMUACEPNVRXHGKR",
                "EFMEBKNTZIJWWLKNEWHG",
                "BNVOINNPVXIBCWFGHUBI",
                "CKHYYRNEPULQJIGRXTIS",
                "QQVVNADWWEGZQNZQENVW",
                "JIMTQTKOOVIHLECAGHYF",
                "LHEDUFUBSRXEZJXPEJFT",
                "EQASWEUELVJYCPBWVXZP",
                "OWTNGSFMCMHIEHACNXHY",
                "SSYUKCSHZSWQOSFWKKLM",
                "ZSXFCXIPWRQOLOKVSDCU",
                "XZKLRPKDCVSDNPIROQHL",
                "JXZVNMQGPTAMUMZNBLQF",
                "GIIWXRNOJWZTTAQJMGPD",
                "BRRVDRKGEBMNLWJLPYZZ",
                "VYUQAKZNSQQUJIROBCVH",
                "DJUQHDBXECYBCURDGTSY",
                "LISXSKLVMIDRTXJBDNYJ",
                "PYKUSDXYYPYKZRHUDURR",
                "DWKYWTZZGZIYZUSRXRRY",
                "IQIJJRDONXFSTPRPKQQT",
                "SARRULLUCCSMUCVFVBTI",
                "YABTRULCMBVECOWYZJSD",
                "NMPIQMNLPJWPJZJBTUDF",
                "XAMBOKAPTUSGHJQZXELN",
                "PJCYINBDHGIHGWIWGILZ",
                "FFIOOYNMEAZTJDURRXUA",
                "EFHMBQJIAWJHCTVSSJEW",
                "JFSTJOMALJCROKERCPBE",
                "LLMPGJIYSMXEURZFFNFQ",
                "WHKMTOEVFFCSSOIZXQZS",
                "EWYANZFUMMLLWVXPLBNQ",
                "JPKBFSAEKCYRYYROXXIM",
                "LVZHSWXDAMVJDIKIANON",
                "PNEPLXDLWOZIJYPCUOHW",
                "AFFFNSNNHCAYRGNEETPA",
                "HOKQMASJQCFTHNYUHOJO",
                "SMMJSZNYSDBBTLSILMRE",
                "OYXVNVRUJBIBPUMJWCIQ",
                "FJSAUKIIYBMNCLKPICMS",
                "FUVWRKFPMNFTYZTVJEFK",
                "FTXJEJZMNNGSJEOAOURA",
                "JZVKYOHKSMUAFTJLCKZQ",
                "XGKHMZJAVDCGCXSANZKI",
                "LEKSZTDCGFSDLCMXDYZA",
                "BDJDABFPBQXMWHHYDMAJ",
                "RSOEWDDCBCCEHLJJNOZQ",
                "GYEFILDLYFWRZKWVPZXS",
                "ECWNNHXCYWSGUXLEIQPI",
                "XLAWYYSNZRIFTETJMQLM",
                "MESIDGNNWEWUSYSSYKHX",
                "EPDXUWIIOUUAAOKDUZQR",
                "GONYOFQMSZKYPPXLLGVZ",
                "ARBCFNFAPXTVOIVCPNRJ",
                "MBHBQFODLJELAHPIWWIL",
                "TBGJLDOAQFKDGREYWVDJ",
                "EJWHQLPMHXADAIMLMALC",
                "FXFNPMNNHQXNZTURFLGM",
                "KIPKQEXCGLHOIOBZARNJ",
                "JMZLFVCMHKBTSSGJWDNF",
                "QWTZLWANNNXXBYIHTMVC",
                "XWWPPCANHOSYKNZXKZLX",
                "PKWQIEZDTVGQTEHKGIAN",
                "YSNKIMISMTPBFMRNSTSN",
                "OADJELUKVUATONFWANOO",
                "IGPNUICOBVCRVHBAUXMP",
                "ROKHEQEEDUUMAJBWTELX",
                "BNQWUTYPQNEJBRRFHXLM",
                "RFAUQCQKIBJJOZFLTGAJ",
                "TGTUXMCGJNTCVTWLXNXF",
                "QGOFIWSBCUMVAHRATTIE",
                "JBHEXDRUSPAJXQQFMIGQ",
                "CVLECFGYAPCJQJPPPHMH",
                "YMQVEGDROLHSGVXLCDJC",
                "SLOLXFCMMOTMCKKHQNAH",
                "YJZHEYSIEBLWOBJLGOZV",
                "CTHFFROVGOEHXGOEEIMI",
                "JZHZASNHGMELFLSKFGIN",
                "UOUTUKXBSMLDLSDONQVV",
                "CZGKMYUTGEHCTBWNOVQG",
                "HCKTUPHJFEFJFNTTOQNU",
                "UUZNXVDLQTSAVETSTCDA",
                "GIJNYFGMVTIRPHHNEKAX",
                "FUXBYSVRUYTCJFPHKVVH",
                "RFYIPHVVRYSXSRARJXKD",
                "VEFGLWNVUKELSETHMRCF",
                "PXCJOEAYBNBZTJFEFVBZ",
                "FFMXJIGVBJBSGFBWMEUP",
                "RYOKHUQMRROYWCWHKEFL",
                "NGDVNFSZJORCMFMTBEIS",
                "VYRTAPALTFWJNCGBJACS",
                "PVUBBIXEMHXJFQCFHCQC",
                "KPLXTUACUFULAQPDAOIO",
                "VHXAZZHGDAIPRWNKSPMO",
                "WIAXARAAFKOARLCSMJYR",
                "JJHCHWMZLAPKIPHIIJKN",
                "WAPNLRGZDGTORARYYDZL",
                "GPVOGCZPOLEKMUZZNHZS",
                "OUHHUAIUFHFLYBCHFBYT",
                "MCFAWFAMOBEEVNMRNULT",
                "DQEERILZJJSYNAYMFAYV",
                "BCAYSMPFIAALTHPMPCLB",
                "NGZBGZNNANIDRICJWRRE",
                "URQNYHBQKNRZTQABRPOR",
                "CWXUHZFDQWIMOABOHDET",
                "SVTLNVOHNCAPAXLHWRLP",
                "NTBDTDSCGYWYURLJMZQZ",
                "BRRBQELNVWCLRDOMGIOO",
                "HMMDDZOSYHTBAKFQPQDM",
                "MHXFLORTYFIHSWMXWBPW",
                "IJAITFAKXEXLNWQYMHUL",
                "OEUICHGYIVXSEZCAECMD",
                "IJOWIEWUNSHDWCMZJSZT",
                "PYLWXPYBRKGCWUAEYWAN",
                "PIRNMDMXXOQOMDKKSINJ",
                "VUNRONVPMXEDHVQTAFQZ",
                "TIOHLARDJHPEDCXRSSIE",
                "RPHZMZSNELOZVEHHFAMQ",
                "HDWKITEANOGEDNDQMYFT",
                "LTSGYBPDCCVJFRWPKAPX",
                "QVBUKFKZFRUQMMWKOMPS",
                "QKDXBZNNBEKSAMOMTANY",
                "RHQDWMQMYFEQSHOVJBJK",
                "FVEHHSUCUJCLRSRNHHZF",
                "OFYIOMEXNPKSKQAUJWYD",
                "HBRYVINCPOKFTIOKUSHH",
                "JTBTKDPVBOAJRRHMZXPQ",
                "LZWHHMRDGAKPUNKERABS",
                "QBDHTLVUKKNVLLEUXXXD",
                "YJUUZEAQGBKYCOFVBDSL",
                "PFIBQNXNKXSKIMEHSEXZ",
                "FIXIYFFZIXMZCUAUJAJU",
                "XBEFNLNIPMHVWGFUNKVX",
                "IHXMCZHLZQHWUOEJZRRQ",
                "DYNAHSWUFSUNZRBDQKRQ",
                "DAOXOSGPLYIPYVRHONET",
                "HYIHRLMJWDBZEQYUKEMW",
                "EULFPEOFRSABSIIJUWTS",
                "AURGMPAXVOTCIGHAKXFD",
                "QGEIQOUKLPENJVTWMVVK",
                "KOMUUVUGSAJKGOTYEPLP",
                "EPCPNXNZTIJFWXZSSUYN",
                "WIXCYSCEHNUNDYDQWQRR",
                "ZDWXAXQVROINYFRYAUDH",
                "HZVMZACXQUORZMPZKFUD",
                "VETWMKWMGZVQASCASHXJ",
                "DOACARDMYYSUELSQXOCG",
                "QYWQQAQJJQUOEWQGOWVM",
                "WNIAAARXPTFFTDXKGQVP",
                "GREMNWUDUPQQEAREBKES",
                "FJZZPWLVOGKUXQIMPDQJ",
                "UIABITHLDNDIZEHOBUJR",
                "AVMZMWMDBCOYMQZUJIGO",
                "WJXVQGJTBSKDNWFBVRGW",
                "VVWHLVDVEJJCVIXLRIES",
                "AOXPNCTKVZIQWFZIADFG",
                "OQIJZHWQPAKRRHJGKCQF",
                "DYYADZKGEPOTFXCGGBYW",
                "BINUSWAEASLGRLGWLQCP",
                "HTIOSNVYOVURGKOAIQEL",
                "JRRCDXAQPDHYYSMQHJOX",
                "FLONXENHVTSGKJIPIIHZ",
                "NPXLJKDQVSNAFDPCICJF",
                "XCLKNVZWDJVTAVGJFKZA",
                "EMDJRSNZXYEWCPGQMIOS",
                "RLLRGTALFBOLPTWGNJGM",
                "KMJMEPEQXSIQEVHKRJYW",
                "KOKZHGGUSOHCCQOGHTXH",
                "NHXTDFEUOESBSCCBJKXD",
                "YEFBWVJGQGNEOKZTRDNI",
                "JHJDKLGVWEYWIDZHAJPR",
                "PCXFMWYECNMNVXTHIZCG",
                "DAFOFEXFNMYDOXKCWLGA",
                "AUNVTIEEIGKLGPZLUWTJ",
                "IRMYRZBNKJPMEEKZNODV",
                "VOGBFIPBGKLRBZPUYQJK",
                "AYXGFHFSVJNSZVUGFLIM",
                "VVDYUUVVLEHNFEVKNCCL",
                "NRDOOZVUMFIHANIWHDRU",
                "JZHOFEYVHCGWTLLILGEX",
                "LOHNBRJKWDFFCOUJVUEE",
                "XMAQYLALTGKEUTTXKDKG",
                "GROKHKVCEAGBMHUMUUXO",
                "DIUZBOZOTJWBAKNHUIKZ",
                "ISCXBWJWTJMYTGXUWWKR",
                "FHSHTFRQODPYVTVXSHVL",
                "SHJLPIHMFSDMBYUUDNKT",
                "QBSLXPKPYHCQOLBGTLSA",
                "FXNGVJCBWPUOSMZPEMEC",
                "TGTKTWQPHKPOHEUDPZGN",
                "OABGPDWTPCVKLQUEPMVY",
                "WLNERJJHIPWWRYFGDBZU",
                "FXEQPBXENSDKDSOXBZGK",
                "QCIHCNOFOPZWOGMGHJKU",
                "CPGHJWELVKXLPFVRTLZJ",
                "AAFRGSXPDJMFBSPKPVVM",
                "GSAXYVQTGPCISIZACYQF",
                "ICNJUEVLZTYFLYELTVGZ",
                "MJJETJFVJXCRZRCVVAHV",
                "TFCGDHUYCAZQJIVCTCZD",
                "ZCWYTBVPBCMUHOAMVUKZ",
                "XLQGUNLPRMSQORQKSLBV",
                "ONPXDRKZOWALISTEFGTW",
                "TOOJFETZSWUILLFPCRQS",
                "QSFALZESFZRYNFIUMDVG",
                "APONCVEHPUZFNFHAGLSL",
                "MLMCTUYFZUNBLBPOYTVN",
                "QUUFBBFHOZVBLHFEDDLC",
                "XYEJBVXBQUPGOJNSLSZZ",
                "UUCFDHLGLWJKWPTZMSAC",
                "MRLDBYVOTWPNTSSWBDFO",
                "BOZZFSYRNATZSGEVFZJY",
                "YALTUFRWKWMLMLKRGKKT",
                "KGUCMZXRYIRYLETFJLDV",
                "HQGWDSPJEACPGXTSWTMW",
                "BFXOKQWVBBRLTZHXSWGW",
                "YJNEIHZEALCDQZUCQQYT",
                "RPELONIIMQHKZURJDQNF",
                "BSLTRFWJVWDOLJBBXLKL",
                "CTXDNONTECYHULDMQBVN",
                "XAEKKFNJRXUTSRWGIJBM",
                "MBWINZUFCSVZUZLEGYNZ",
                "YJSQDRYLCBZQDVZSWVXY",
                "PUZKVKOCLEBJNWBSPADT",
                "BDKGYLYXGYVYSXIOHYSU",
                "ETDURHMIHQCKVMTVZRSF",
                "PQFKNNYWOQRSLWMDDBNM",
                "RPZMDSHCJCKBSPLFFLBT",
                "BULORATUBHHUWGIAYRCJ",
                "TMMLCXSJKWCLQPAJRTEU",
                "ANOZTYZTQBEJQRXUQRDB",
                "PFOIWQROKXIMKZNDXMYN",
                "QDZGUWCKPFLFMCNISGYE",
                "EHTOGGUDTSRJVSRROTCF",
                "APKORZWKGVQKEJYKQSPJ",
                "NIUIANAQIEWKVIYNIUZQ",
                "RPAXZAJRVZAIJWSKLSCT",
                "YYDUJDHRZIJRZJOALYRG",
                "ZTQIPJUCDXVCVAWGDFXD",
                "NGWORMPDMGLNAEWRNQUQ",
                "PRSNSOTXTRCIZAXTNMYB",
                "ULPWPNOCDKVTBNIVEBVZ",
                "UZKUAHPPVNQRYHOOUESA",
                "ONVRBDNHEKGZJQVJZKYW",
                "XROXAELVIEVYRQPUVCBZ",
                "OKAYAVHCFIAEBOCBUNWC",
                "TTCNLSHGWJILTIJVESZL",
                "AAQDQSFLHDPDZSQKMXTI",
                "IBTDJEBPXABXCTBTNIGW",
                "LXZKRPXDPQMXRHDCMEUJ",
                "GVIJQLEDVMBHJBTDSSGH",
                "IUHBCKGQOABUXJFPXJSS",
                "XTBJWXMPPUYAPFBTPJJF",
                "JKCIVHXUTRNQNOBJNNAD",
                "IZDZEGSWQDBZPFKMNHHI",
                "BWAOKCXYRADBZGAFMUBC",
                "ZFEOKQBZXKJAGKOSOOSF",
                "OVHNDJSQGWUFDAUNQXPQ",
                "JYQPKFHYVCEJXNWBWQTC",
                "OPKRQEHIDYYMWRDHYKFT",
                "OLCMYAPXSKBHZLARRHAU",
                "FAIERLNRYSKMGMAEOPDJ",
                "BFQBQSUKAUEHXPNOAAGY",
                "VSLBHLHVDLEESWHIPCUR",
                "YZAVQOMQQURLMEOTRWRU",
                "HXBZWKJNMEGNFGIVWWNN",
                "QEAFIPACLRYURZVPMECY",
                "KILRQWOPSCELIEQTVQVG",
                "KTCDVXSHEWHOEVGWRULL",
                "YPWHUOAPHXYTQAYLYQUC",
                "MCSSXAOQXABVPAELQGDX",
                "DBSWDQJDIEHWGAOFAFVZ",
                "FYXWABKRKNQNQJJTBTXK",
                "ZEGHGVMJAJIHHFFIJPBT",
                "CRISAUOENLOORUVYRJHT",
                "SPCBXILGZMBCEJWGDKKS",
                "XAIPXDNQOUMILOMIYXQY",
                "MRCQDAYGLLBILJZKPMBD",
                "INMUDACCXVCJMEBPECYR",
                "NZCAKBLZQMDYBRSETXIQ",
                "SMCGSDYZFYQUZUVJWILO",
                "UQMXHHDCGOSAAWGTAGSH",
                "EKEFFZPBHAPDQDCZKFBQ",
                "TVQUSZPUHHDMRHTWIKZR",
                "MQUEUWFGEIZXEPTYQIUY",
                "PXMJHFHPQHHEZDJVCOCG",
                "XDFDUBBLJXLBUXKDETTW",
                "ACBCHKXJABRXEXAZYDMJ",
                "AXMXUYAYSVXUZYWHIUQI",
                "XKIEJKDJQRSSOFPKDSKV",
                "PHQPFOWPKOAIYIMHURQK",
                "ILDYQUIVOSTECLVHZTXK",
                "HZUIHIRBZKMJVRHNLRKC",
                "JDGNQDVQWUCFTYNCGFFH",
                "PTQMKZZYQJABPIPFLMXJ",
                "GBOBZCDFJIMACEMODNMV",
                "YOXNWMVJASSGUHHVLMBU",
                "WPWAWIPZXBVVSULOIIAI",
                "CSOYBXUMLVIHMEIIOXKL",
                "AFJUBWLJELRGFFFHEZVP",
                "WGYKMITBHFOKMZENVPWZ",
                "ANIGUPPAOMPMSPWFYRIF",
                "WYPIYWXVLTXMGFUCULCK",
                "XTYQJWXJQHOOFGXFCWBP",
                "QYDYFXBZKDLIZLAIHZRX",
                "GHMNPLTTHUJZUOYZOZAY",
                "ENGDYINFHGFPQRDHCWBL",
                "SMLOCJNQKNPQCVWAEJFN",
                "SKDIDGRHESTYGGMJRBZB",
                "QQTSOPSUBZHTKKDPSUXY",
                "PSYXYKIPNKSDALXODPIE",
                "RSZBEESXAPXPHWPFIZWW",
                "JOBMABCDQLJHFIKJMDIM",
                "UGECEVJMUGKGWOSWPUBH",
                "HKRMUBYIGGXDOBHSYQFS",
                "YRYVFQTUNVEWHVLCYJMF",
                "PJKGMRYKJFDIXDFEWYBJ",
                "VFFFASJYBVFTFPZRIXCS",
                "FHCCKHGGHJPFOXKQPTPT",
                "QWMVMNPUMTORAQTKZCTJ",
                "NKQCJASZVJULGIJUVYQH",
                "TFZTXUFZYYIMJYOSAITX",
                "UNICVTYSTOAMVBHVVNUU",
                "LEGWCWPEGKBCYLEVFCOA",
                "TQPQRWLOJHKXLSTPOKTX",
                "VUZTIGQPKGPDYEWPDHGM",
                "RQJCJFSZPNYKKAFSGWHS",
                "EYYDFUUIDCWUTIZENRFC",
                "GENQGUIMSRGXQECXYWFE",
                "BBYUJXAYQFBZLQPRKAFF",
                "RMCJQGGPENVFRTZCTZBL",
                "HEKSUCMGCRLTDPDUVLLA",
                "ZGFQBHSWIVKPZWKVYWCA",
                "NPWTFBNCMACNIKFJRYIZ",
                "VSRVQBQPZUROKPHPQWRF",
                "WWSEGAQXYAYVUPQKSHZT",
                "BTINIREZOYGMUATCAJZA",
                "LZWFRMPJVRFZKNOSGTTU",
                "RBHNCAPELQFWPDBGRQSN",
                "HXOTMCOSVHPOLWBNYQRL",
                "IYHYBKGTCYIMXWFLATEY",
                "DTMORQDRIUCRVJPWVXRX",
                "WZJVXPHAKNYNIMBZCESL",
                "BUEWFTUAQMXONHMLYTLI"
            };
            int __expected = 1043070;
            return do_test(to_vector(answer), __expected, __no);
        }

        // Your custom testcase goes here
        case 5:
            break;
        default: break;
    }
    return 0;
}

int main(int argc, char *argv[]) {
    cout.setf(ios::fixed,ios::floatfield);
    cout.precision(2);
    
    bool mainProcess = true;
    set<int> testCases;
    for (int i = 1; i < argc; i++) {
        if ( string(argv[i]) == "-" ) {
            mainProcess = false;
        } else {
            testCases.insert( atoi(argv[i]) );
        }
    }
    if (testCases.size() == 0) {
        for (int i = 0; i < 5; i++) {
            testCases.insert(i);
        }
    }
    if (mainProcess) {
        cout << "DistinguishableSetDiv1 (500 Points)" << endl << endl;
    }

    int nPassed = 0;
    
    for (int i = 0; i < 5; ++i) {
        if ( testCases.empty()  || testCases.count(i) ) {
            //run
            nPassed += run_testcase(i);
        }
    }
    if (mainProcess) {
        cout << endl << "Passed : " << nPassed << "/" << testCases.size() << " cases" << endl;
        int T = time(NULL) - 1477189411;
        double PT = T / 60.0, TT = 75.0;
        cout << "Time   : " << T / 60 << " minutes " << T % 60 << " secs" << endl;
        cout << "Score  : " << 500 * (0.3 + (0.7 * TT * TT) / (10.0 * PT * PT + TT * TT)) << " points" << endl;
    }
    return 0;
}
// CUT end
